ambta_doctrine_encrypt:
    # If you want, you can use your own Encryptor. Encryptor must implements EncryptorInterface interface
    # Default: Halite
    # encryptor_class: Halite

    # Path where to store the keyfiles
    # Default: '%kernel.project_dir%'
    # secret_directory_path: '%kernel.project_dir%'

    # Secret string
    secret: '%env(CRYPTO_SECRET)%'

    # Use the new wrapped exceptions to avoid deprecation warning
    # See: https://github.com/DoctrineEncryptBundle/DoctrineEncryptBundle/pull/41
    wrap_exceptions: true
