knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(GOOGLE_OAUTH_ID)%'
            client_secret: '%env(GOOGLE_OAUTH_SECRET)%'
            redirect_route: oauth_providers_callback
            redirect_params:
                provider: google
        decidim_inspire:
            type: generic
            provider_class: App\OAuth\DecidimProvider
            provider_options:
                url: https://inspire-staging.platoniq.net
            client_id: '%env(DECIDIM_OAUTH_ID)%'
            client_secret: '%env(DECIDIM_OAUTH_SECRET)%'
            redirect_route: oauth_providers_callback
            redirect_params:
                provider: decidim_inspire