services:
  php:
    volumes:
      # ./docker/dev/php/ssl/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./docker/dev/php/conf.d/opcache.dev.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./docker/dev/php/conf.d/xdebug.dev.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "9000:9000"
      - "9003:9003"
